[app]
# Address to listen.
address = "0.0.0.0:9000"

# No trailing slashes.
root_url = "/"

name = "Niltalk chat"

max_rooms = 1000
max_peers_per_room = 25

# Peer handle format (%s for ID) for peers who don't pick handles.
peer_handle_format = "Peer:%s"

# Length of the randomly generated room ID.
room_id_length = 8

# The number of messages and events (join / leave) etc. that has to be cached
# in a room to send to peers when they first join.
max_cached_messages = 100

# Maximum message length in bytes.
max_message_length = 3000

# Permitted message rate (messages / interval) after which a peer is kicked.
rate_limit_messages = 25
rate_limit_interval = "3s"

# How long will the room id persist in the db before first use?
room_age = "24h"

# Timeout in seconds for which the server will wait when sending
# a message to a peer before closing the connection. Useful for
# kicking out peers with slow connections.
websocket_timeout = "3s"

# Session cookie name.
session_cookie = "niltoken"

# Storage kind, one of redis or memory.
storage = "memory"

# Redis cache server.
# Rooms are cached until they expires. Messages are not cached.
[store]
address = "redis:6379" # Eg: 127.0.0.1:6379
password = ""
db = 0
active_conns = 100
idle_conns = 20
timeout = "3s"

prefix_room = "NIL:ROOM:%s"
prefix_session = "NIL:SESS:ROOM:%s"

path="db.json"

[tor]
enabled=false
ssl=true
# Path to the tor private key path, leave it empty to store your key within the store.
privatekey=""

[ssl]
enabled=false
kind="auto"
address=":443"
domains= [ "localhost" ]

[rooms]
  [rooms.local]
  id="local"
  name="local"
  password=""
  motd="Welcome, type /help to get commands help"
    [rooms.local.growl]
    message="{{.UserName}} is calling you. Open {{.URL}}"
    title="Niltalk notification"
    sound="knadh/static/beep.mp3"
    [[rooms.local.users]]
    name="me1"
    password="azerty"
    growl=true
    [[rooms.local.users]]
    name="me2"
    password="azerty"

[qr]
tor=true
clear="http://some.where.com/"
